import {
  enero_norte_P_1_D_1,
  //   enero_norte_P_1_D_2,
  enero_norte_P_1_D_3,
  enero_norte_P_2_D_1,
  enero_norte_P_2_D_2,
  enero_norte_P_2_D_3,
  enero_norte_P_3_D_1,
  enero_norte_P_3_D_2,
  enero_norte_P_3_D_3,
  enero_norte_P_4_D_1,
  enero_norte_P_4_D_2,
  enero_norte_P_4_D_3,
  enero_norte_P_5_D_1,
  enero_norte_P_5_D_2,
  enero_norte_P_5_D_3,
  enero_norte_P_6_D_1,
  enero_norte_P_6_D_2,
  enero_norte_P_6_D_3,
} from "./meses-estado/1-enero-norte.js";

import {
  enero_sur_P_1_D_1,
  //   enero_sur_P_1_D_2,
  enero_sur_P_1_D_3,
  enero_sur_P_2_D_1,
  enero_sur_P_2_D_2,
  enero_sur_P_2_D_3,
  enero_sur_P_3_D_1,
  enero_sur_P_3_D_2,
  enero_sur_P_3_D_3,
  enero_sur_P_4_D_1,
  enero_sur_P_4_D_2,
  enero_sur_P_4_D_3,
  enero_sur_P_5_D_1,
  enero_sur_P_5_D_2,
  enero_sur_P_5_D_3,
  enero_sur_P_6_D_1,
  enero_sur_P_6_D_2,
  enero_sur_P_6_D_3,
} from "./meses-estado/1-enero-sur.js";
import {
  febrero_norte_P_1_D_1,
  //   febrero_norte_P_1_D_2,
  febrero_norte_P_1_D_3,
  febrero_norte_P_2_D_1,
  febrero_norte_P_2_D_2,
  febrero_norte_P_2_D_3,
  febrero_norte_P_3_D_1,
  febrero_norte_P_3_D_2,
  febrero_norte_P_3_D_3,
  febrero_norte_P_4_D_1,
  febrero_norte_P_4_D_2,
  febrero_norte_P_4_D_3,
  febrero_norte_P_5_D_1,
  febrero_norte_P_5_D_2,
  febrero_norte_P_5_D_3,
  febrero_norte_P_6_D_1,
  febrero_norte_P_6_D_2,
  febrero_norte_P_6_D_3,
} from "./meses-estado/2-febrero-norte.js";
import {
  febrero_sur_P_1_D_1,
  //   febrero_sur_P_1_D_2,
  febrero_sur_P_1_D_3,
  febrero_sur_P_2_D_1,
  febrero_sur_P_2_D_2,
  febrero_sur_P_2_D_3,
  febrero_sur_P_3_D_1,
  febrero_sur_P_3_D_2,
  febrero_sur_P_3_D_3,
  febrero_sur_P_4_D_1,
  febrero_sur_P_4_D_2,
  febrero_sur_P_4_D_3,
  febrero_sur_P_5_D_1,
  febrero_sur_P_5_D_2,
  febrero_sur_P_5_D_3,
  febrero_sur_P_6_D_1,
  febrero_sur_P_6_D_2,
  febrero_sur_P_6_D_3,
} from "./meses-estado/2-febrero-sur.js";
import {
  marzo_norte_P_1_D_1,
  //   marzo_norte_P_1_D_2,
  marzo_norte_P_1_D_3,
  marzo_norte_P_2_D_1,
  marzo_norte_P_2_D_2,
  marzo_norte_P_2_D_3,
  marzo_norte_P_3_D_1,
  marzo_norte_P_3_D_2,
  marzo_norte_P_3_D_3,
  marzo_norte_P_4_D_1,
  marzo_norte_P_4_D_2,
  marzo_norte_P_4_D_3,
  marzo_norte_P_5_D_1,
  marzo_norte_P_5_D_2,
  marzo_norte_P_5_D_3,
  marzo_norte_P_6_D_1,
  marzo_norte_P_6_D_2,
  marzo_norte_P_6_D_3,
} from "./meses-estado/3-marzo-norte.js";
import {
  marzo_sur_P_1_D_1,
  //   marzo_sur_P_1_D_2,
  marzo_sur_P_1_D_3,
  marzo_sur_P_2_D_1,
  marzo_sur_P_2_D_2,
  marzo_sur_P_2_D_3,
  marzo_sur_P_3_D_1,
  marzo_sur_P_3_D_2,
  marzo_sur_P_3_D_3,
  marzo_sur_P_4_D_1,
  marzo_sur_P_4_D_2,
  marzo_sur_P_4_D_3,
  marzo_sur_P_5_D_1,
  marzo_sur_P_5_D_2,
  marzo_sur_P_5_D_3,
  marzo_sur_P_6_D_1,
  marzo_sur_P_6_D_2,
  marzo_sur_P_6_D_3,
} from "./meses-estado/3-marzo-sur.js";

const variablesEneroNorte = {
  enero_norte_P_1_D_1,
  //   enero_norte_P_1_D_2,
  enero_norte_P_1_D_3,
  enero_norte_P_2_D_1,
  enero_norte_P_2_D_2,
  enero_norte_P_2_D_3,
  enero_norte_P_3_D_1,
  enero_norte_P_3_D_2,
  enero_norte_P_3_D_3,
  enero_norte_P_4_D_1,
  enero_norte_P_4_D_2,
  enero_norte_P_4_D_3,
  enero_norte_P_5_D_1,
  enero_norte_P_5_D_2,
  enero_norte_P_5_D_3,
  enero_norte_P_6_D_1,
  enero_norte_P_6_D_2,
  enero_norte_P_6_D_3,
  enero_sur_P_1_D_1,
  //   enero_sur_P_1_D_2,
  enero_sur_P_1_D_3,
  enero_sur_P_2_D_1,
  enero_sur_P_2_D_2,
  enero_sur_P_2_D_3,
  enero_sur_P_3_D_1,
  enero_sur_P_3_D_2,
  enero_sur_P_3_D_3,
  enero_sur_P_4_D_1,
  enero_sur_P_4_D_2,
  enero_sur_P_4_D_3,
  enero_sur_P_5_D_1,
  enero_sur_P_5_D_2,
  enero_sur_P_5_D_3,
  enero_sur_P_6_D_1,
  enero_sur_P_6_D_2,
  enero_sur_P_6_D_3,
  febrero_norte_P_1_D_1,
  //   febrero_norte_P_1_D_2,
  febrero_norte_P_1_D_3,
  febrero_norte_P_2_D_1,
  febrero_norte_P_2_D_2,
  febrero_norte_P_2_D_3,
  febrero_norte_P_3_D_1,
  febrero_norte_P_3_D_2,
  febrero_norte_P_3_D_3,
  febrero_norte_P_4_D_1,
  febrero_norte_P_4_D_2,
  febrero_norte_P_4_D_3,
  febrero_norte_P_5_D_1,
  febrero_norte_P_5_D_2,
  febrero_norte_P_5_D_3,
  febrero_norte_P_6_D_1,
  febrero_norte_P_6_D_2,
  febrero_norte_P_6_D_3,
  febrero_sur_P_1_D_1,
  //   febrero_sur_P_1_D_2,
  febrero_sur_P_1_D_3,
  febrero_sur_P_2_D_1,
  febrero_sur_P_2_D_2,
  febrero_sur_P_2_D_3,
  febrero_sur_P_3_D_1,
  febrero_sur_P_3_D_2,
  febrero_sur_P_3_D_3,
  febrero_sur_P_4_D_1,
  febrero_sur_P_4_D_2,
  febrero_sur_P_4_D_3,
  febrero_sur_P_5_D_1,
  febrero_sur_P_5_D_2,
  febrero_sur_P_5_D_3,
  febrero_sur_P_6_D_1,
  febrero_sur_P_6_D_2,
  febrero_sur_P_6_D_3,
  marzo_norte_P_1_D_1,
  //   marzo_norte_P_1_D_2,
  marzo_norte_P_1_D_3,
  marzo_norte_P_2_D_1,
  marzo_norte_P_2_D_2,
  marzo_norte_P_2_D_3,
  marzo_norte_P_3_D_1,
  marzo_norte_P_3_D_2,
  marzo_norte_P_3_D_3,
  marzo_norte_P_4_D_1,
  marzo_norte_P_4_D_2,
  marzo_norte_P_4_D_3,
  marzo_norte_P_5_D_1,
  marzo_norte_P_5_D_2,
  marzo_norte_P_5_D_3,
  marzo_norte_P_6_D_1,
  marzo_norte_P_6_D_2,
  marzo_norte_P_6_D_3,
  marzo_sur_P_1_D_1,
  //   marzo_sur_P_1_D_2,
  marzo_sur_P_1_D_3,
  marzo_sur_P_2_D_1,
  marzo_sur_P_2_D_2,
  marzo_sur_P_2_D_3,
  marzo_sur_P_3_D_1,
  marzo_sur_P_3_D_2,
  marzo_sur_P_3_D_3,
  marzo_sur_P_4_D_1,
  marzo_sur_P_4_D_2,
  marzo_sur_P_4_D_3,
  marzo_sur_P_5_D_1,
  marzo_sur_P_5_D_2,
  marzo_sur_P_5_D_3,
  marzo_sur_P_6_D_1,
  marzo_sur_P_6_D_2,
  marzo_sur_P_6_D_3,
};

const depart = document.querySelectorAll(".container-departamento");

depart.forEach((depart) => {
  const img = depart.querySelector("img");
  img.addEventListener("click", clickDepart);
});

function clickDepart(event) {
  const departSelect = event.currentTarget.id;
  const data = departSelect.replace(
    /_(p|d)_/g,
    (match, p1) => `_${p1.toUpperCase()}_`
  );

  if (data in variablesEneroNorte) {
    const contenidoVariable = variablesEneroNorte[data];
    if (contenidoVariable.status === "Disponible") {
      const unidadCotizador = document.getElementById("unidad-cotizador");
      const areaCotizador = document.getElementById("area-cotizador");
      const precioCotizador = document.getElementById("precio-cotizador");
      const valorInput = document.getElementById("enganche-valor");

      const numeroFormateado = contenidoVariable.precio.toLocaleString(
        "es-MX",
        {
          style: "currency",
          currency: "MXN",
        }
      );
      valorInput.value = numeroFormateado;
      unidadCotizador.innerHTML = contenidoVariable.apto;
      areaCotizador.innerHTML = contenidoVariable.metros;
      precioCotizador.innerHTML = "$ " + contenidoVariable.precio;
      const modal = document.getElementById("modal-cotizador");
      modal.style.display = "block";
    }
  }
}
