import {
  enero_norte_P_1_D_1,
  //   enero_norte_P_1_D_2,
  enero_norte_P_1_D_3,
  enero_norte_P_2_D_1,
  enero_norte_P_2_D_2,
  enero_norte_P_2_D_3,
  enero_norte_P_3_D_1,
  enero_norte_P_3_D_2,
  enero_norte_P_3_D_3,
  enero_norte_P_4_D_1,
  enero_norte_P_4_D_2,
  enero_norte_P_4_D_3,
  enero_norte_P_5_D_1,
  enero_norte_P_5_D_2,
  enero_norte_P_5_D_3,
  enero_norte_P_6_D_1,
  enero_norte_P_6_D_2,
  enero_norte_P_6_D_3,
} from "./meses-estado/1-enero-norte.js";

import {
  enero_sur_P_1_D_1,
  //   enero_sur_P_1_D_2,
  enero_sur_P_1_D_3,
  enero_sur_P_2_D_1,
  enero_sur_P_2_D_2,
  enero_sur_P_2_D_3,
  enero_sur_P_3_D_1,
  enero_sur_P_3_D_2,
  enero_sur_P_3_D_3,
  enero_sur_P_4_D_1,
  enero_sur_P_4_D_2,
  enero_sur_P_4_D_3,
  enero_sur_P_5_D_1,
  enero_sur_P_5_D_2,
  enero_sur_P_5_D_3,
  enero_sur_P_6_D_1,
  enero_sur_P_6_D_2,
  enero_sur_P_6_D_3,
} from "./meses-estado/1-enero-sur.js";
import {
  febrero_norte_P_1_D_1,
  //   febrero_norte_P_1_D_2,
  febrero_norte_P_1_D_3,
  febrero_norte_P_2_D_1,
  febrero_norte_P_2_D_2,
  febrero_norte_P_2_D_3,
  febrero_norte_P_3_D_1,
  febrero_norte_P_3_D_2,
  febrero_norte_P_3_D_3,
  febrero_norte_P_4_D_1,
  febrero_norte_P_4_D_2,
  febrero_norte_P_4_D_3,
  febrero_norte_P_5_D_1,
  febrero_norte_P_5_D_2,
  febrero_norte_P_5_D_3,
  febrero_norte_P_6_D_1,
  febrero_norte_P_6_D_2,
  febrero_norte_P_6_D_3,
} from "./meses-estado/2-febrero-norte.js";
import {
  febrero_sur_P_1_D_1,
  //   febrero_sur_P_1_D_2,
  febrero_sur_P_1_D_3,
  febrero_sur_P_2_D_1,
  febrero_sur_P_2_D_2,
  febrero_sur_P_2_D_3,
  febrero_sur_P_3_D_1,
  febrero_sur_P_3_D_2,
  febrero_sur_P_3_D_3,
  febrero_sur_P_4_D_1,
  febrero_sur_P_4_D_2,
  febrero_sur_P_4_D_3,
  febrero_sur_P_5_D_1,
  febrero_sur_P_5_D_2,
  febrero_sur_P_5_D_3,
  febrero_sur_P_6_D_1,
  febrero_sur_P_6_D_2,
  febrero_sur_P_6_D_3,
} from "./meses-estado/2-febrero-sur.js";
import {
  marzo_norte_P_1_D_1,
  //   marzo_norte_P_1_D_2,
  marzo_norte_P_1_D_3,
  marzo_norte_P_2_D_1,
  marzo_norte_P_2_D_2,
  marzo_norte_P_2_D_3,
  marzo_norte_P_3_D_1,
  marzo_norte_P_3_D_2,
  marzo_norte_P_3_D_3,
  marzo_norte_P_4_D_1,
  marzo_norte_P_4_D_2,
  marzo_norte_P_4_D_3,
  marzo_norte_P_5_D_1,
  marzo_norte_P_5_D_2,
  marzo_norte_P_5_D_3,
  marzo_norte_P_6_D_1,
  marzo_norte_P_6_D_2,
  marzo_norte_P_6_D_3,
} from "./meses-estado/3-marzo-norte.js";
import {
  marzo_sur_P_1_D_1,
  //   marzo_sur_P_1_D_2,
  marzo_sur_P_1_D_3,
  marzo_sur_P_2_D_1,
  marzo_sur_P_2_D_2,
  marzo_sur_P_2_D_3,
  marzo_sur_P_3_D_1,
  marzo_sur_P_3_D_2,
  marzo_sur_P_3_D_3,
  marzo_sur_P_4_D_1,
  marzo_sur_P_4_D_2,
  marzo_sur_P_4_D_3,
  marzo_sur_P_5_D_1,
  marzo_sur_P_5_D_2,
  marzo_sur_P_5_D_3,
  marzo_sur_P_6_D_1,
  marzo_sur_P_6_D_2,
  marzo_sur_P_6_D_3,
} from "./meses-estado/3-marzo-sur.js";

import {
  abril_norte_P_1_D_1,
  //   abril_norte_P_1_D_2,
  abril_norte_P_1_D_3,
  abril_norte_P_2_D_1,
  abril_norte_P_2_D_2,
  abril_norte_P_2_D_3,
  abril_norte_P_3_D_1,
  abril_norte_P_3_D_2,
  abril_norte_P_3_D_3,
  abril_norte_P_4_D_1,
  abril_norte_P_4_D_2,
  abril_norte_P_4_D_3,
  abril_norte_P_5_D_1,
  abril_norte_P_5_D_2,
  abril_norte_P_5_D_3,
  abril_norte_P_6_D_1,
  abril_norte_P_6_D_2,
  abril_norte_P_6_D_3,
} from "./meses-estado/4-abril-norte.js";
import {
  abril_sur_P_1_D_1,
  //   abril_sur_P_1_D_2,
  abril_sur_P_1_D_3,
  abril_sur_P_2_D_1,
  abril_sur_P_2_D_2,
  abril_sur_P_2_D_3,
  abril_sur_P_3_D_1,
  abril_sur_P_3_D_2,
  abril_sur_P_3_D_3,
  abril_sur_P_4_D_1,
  abril_sur_P_4_D_2,
  abril_sur_P_4_D_3,
  abril_sur_P_5_D_1,
  abril_sur_P_5_D_2,
  abril_sur_P_5_D_3,
  abril_sur_P_6_D_1,
  abril_sur_P_6_D_2,
  abril_sur_P_6_D_3,
} from "./meses-estado/4-abril-sur.js";

import {
  junio_norte_P_1_D_1,
  //   junio_norte_P_1_D_2,
  junio_norte_P_1_D_3,
  junio_norte_P_2_D_1,
  junio_norte_P_2_D_2,
  junio_norte_P_2_D_3,
  junio_norte_P_3_D_1,
  junio_norte_P_3_D_2,
  junio_norte_P_3_D_3,
  junio_norte_P_4_D_1,
  junio_norte_P_4_D_2,
  junio_norte_P_4_D_3,
  junio_norte_P_5_D_1,
  junio_norte_P_5_D_2,
  junio_norte_P_5_D_3,
  junio_norte_P_6_D_1,
  junio_norte_P_6_D_2,
  junio_norte_P_6_D_3,
} from "./meses-estado/5-junio-norte.js";
import {
  junio_sur_P_1_D_1,
  //   junio_sur_P_1_D_2,
  junio_sur_P_1_D_3,
  junio_sur_P_2_D_1,
  junio_sur_P_2_D_2,
  junio_sur_P_2_D_3,
  junio_sur_P_3_D_1,
  junio_sur_P_3_D_2,
  junio_sur_P_3_D_3,
  junio_sur_P_4_D_1,
  junio_sur_P_4_D_2,
  junio_sur_P_4_D_3,
  junio_sur_P_5_D_1,
  junio_sur_P_5_D_2,
  junio_sur_P_5_D_3,
  junio_sur_P_6_D_1,
  junio_sur_P_6_D_2,
  junio_sur_P_6_D_3,
} from "./meses-estado/5-junio-sur.js";

import {
  julio_norte_P_1_D_1,
  //   julio_norte_P_1_D_2,
  julio_norte_P_1_D_3,
  julio_norte_P_2_D_1,
  julio_norte_P_2_D_2,
  julio_norte_P_2_D_3,
  julio_norte_P_3_D_1,
  julio_norte_P_3_D_2,
  julio_norte_P_3_D_3,
  julio_norte_P_4_D_1,
  julio_norte_P_4_D_2,
  julio_norte_P_4_D_3,
  julio_norte_P_5_D_1,
  julio_norte_P_5_D_2,
  julio_norte_P_5_D_3,
  julio_norte_P_6_D_1,
  julio_norte_P_6_D_2,
  julio_norte_P_6_D_3,
} from "./meses-estado/6-julio-norte.js";
import {
  julio_sur_P_1_D_1,
  //   julio_sur_P_1_D_2,
  julio_sur_P_1_D_3,
  julio_sur_P_2_D_1,
  julio_sur_P_2_D_2,
  julio_sur_P_2_D_3,
  julio_sur_P_3_D_1,
  julio_sur_P_3_D_2,
  julio_sur_P_3_D_3,
  julio_sur_P_4_D_1,
  julio_sur_P_4_D_2,
  julio_sur_P_4_D_3,
  julio_sur_P_5_D_1,
  julio_sur_P_5_D_2,
  julio_sur_P_5_D_3,
  julio_sur_P_6_D_1,
  julio_sur_P_6_D_2,
  julio_sur_P_6_D_3,
} from "./meses-estado/6-julio-sur.js";

import {
  agosto_norte_P_1_D_1,
  //   agosto_norte_P_1_D_2,
  agosto_norte_P_1_D_3,
  agosto_norte_P_2_D_1,
  agosto_norte_P_2_D_2,
  agosto_norte_P_2_D_3,
  agosto_norte_P_3_D_1,
  agosto_norte_P_3_D_2,
  agosto_norte_P_3_D_3,
  agosto_norte_P_4_D_1,
  agosto_norte_P_4_D_2,
  agosto_norte_P_4_D_3,
  agosto_norte_P_5_D_1,
  agosto_norte_P_5_D_2,
  agosto_norte_P_5_D_3,
  agosto_norte_P_6_D_1,
  agosto_norte_P_6_D_2,
  agosto_norte_P_6_D_3,
} from "./meses-estado/7-agosto-norte.js";
import {
  agosto_sur_P_1_D_1,
  //   agosto_sur_P_1_D_2,
  agosto_sur_P_1_D_3,
  agosto_sur_P_2_D_1,
  agosto_sur_P_2_D_2,
  agosto_sur_P_2_D_3,
  agosto_sur_P_3_D_1,
  agosto_sur_P_3_D_2,
  agosto_sur_P_3_D_3,
  agosto_sur_P_4_D_1,
  agosto_sur_P_4_D_2,
  agosto_sur_P_4_D_3,
  agosto_sur_P_5_D_1,
  agosto_sur_P_5_D_2,
  agosto_sur_P_5_D_3,
  agosto_sur_P_6_D_1,
  agosto_sur_P_6_D_2,
  agosto_sur_P_6_D_3,
} from "./meses-estado/8-agosto-sur.js";

import {
  septiembre_norte_P_1_D_1,
  //   septiembre_norte_P_1_D_2,
  septiembre_norte_P_1_D_3,
  septiembre_norte_P_2_D_1,
  septiembre_norte_P_2_D_2,
  septiembre_norte_P_2_D_3,
  septiembre_norte_P_3_D_1,
  septiembre_norte_P_3_D_2,
  septiembre_norte_P_3_D_3,
  septiembre_norte_P_4_D_1,
  septiembre_norte_P_4_D_2,
  septiembre_norte_P_4_D_3,
  septiembre_norte_P_5_D_1,
  septiembre_norte_P_5_D_2,
  septiembre_norte_P_5_D_3,
  septiembre_norte_P_6_D_1,
  septiembre_norte_P_6_D_2,
  septiembre_norte_P_6_D_3,
} from "./meses-estado/9-septiembre-norte.js";
import {
  septiembre_sur_P_1_D_1,
  //   septiembre_sur_P_1_D_2,
  septiembre_sur_P_1_D_3,
  septiembre_sur_P_2_D_1,
  septiembre_sur_P_2_D_2,
  septiembre_sur_P_2_D_3,
  septiembre_sur_P_3_D_1,
  septiembre_sur_P_3_D_2,
  septiembre_sur_P_3_D_3,
  septiembre_sur_P_4_D_1,
  septiembre_sur_P_4_D_2,
  septiembre_sur_P_4_D_3,
  septiembre_sur_P_5_D_1,
  septiembre_sur_P_5_D_2,
  septiembre_sur_P_5_D_3,
  septiembre_sur_P_6_D_1,
  septiembre_sur_P_6_D_2,
  septiembre_sur_P_6_D_3,
} from "./meses-estado/9-septiembre-sur.js";

import {
  octubre_norte_P_1_D_1,
  //   octubre_norte_P_1_D_2,
  octubre_norte_P_1_D_3,
  octubre_norte_P_2_D_1,
  octubre_norte_P_2_D_2,
  octubre_norte_P_2_D_3,
  octubre_norte_P_3_D_1,
  octubre_norte_P_3_D_2,
  octubre_norte_P_3_D_3,
  octubre_norte_P_4_D_1,
  octubre_norte_P_4_D_2,
  octubre_norte_P_4_D_3,
  octubre_norte_P_5_D_1,
  octubre_norte_P_5_D_2,
  octubre_norte_P_5_D_3,
  octubre_norte_P_6_D_1,
  octubre_norte_P_6_D_2,
  octubre_norte_P_6_D_3,
} from "./meses-estado/10-octubre-norte.js";
import {
  octubre_sur_P_1_D_1,
  //   octubre_sur_P_1_D_2,
  octubre_sur_P_1_D_3,
  octubre_sur_P_2_D_1,
  octubre_sur_P_2_D_2,
  octubre_sur_P_2_D_3,
  octubre_sur_P_3_D_1,
  octubre_sur_P_3_D_2,
  octubre_sur_P_3_D_3,
  octubre_sur_P_4_D_1,
  octubre_sur_P_4_D_2,
  octubre_sur_P_4_D_3,
  octubre_sur_P_5_D_1,
  octubre_sur_P_5_D_2,
  octubre_sur_P_5_D_3,
  octubre_sur_P_6_D_1,
  octubre_sur_P_6_D_2,
  octubre_sur_P_6_D_3,
} from "./meses-estado/10-octubre-sur.js";

import {
  noviembre_norte_P_1_D_1,
  //   noviembre_norte_P_1_D_2,
  noviembre_norte_P_1_D_3,
  noviembre_norte_P_2_D_1,
  noviembre_norte_P_2_D_2,
  noviembre_norte_P_2_D_3,
  noviembre_norte_P_3_D_1,
  noviembre_norte_P_3_D_2,
  noviembre_norte_P_3_D_3,
  noviembre_norte_P_4_D_1,
  noviembre_norte_P_4_D_2,
  noviembre_norte_P_4_D_3,
  noviembre_norte_P_5_D_1,
  noviembre_norte_P_5_D_2,
  noviembre_norte_P_5_D_3,
  noviembre_norte_P_6_D_1,
  noviembre_norte_P_6_D_2,
  noviembre_norte_P_6_D_3,
} from "./meses-estado/11-noviembre-norte.js";
import {
  noviembre_sur_P_1_D_1,
  //   noviembre_sur_P_1_D_2,
  noviembre_sur_P_1_D_3,
  noviembre_sur_P_2_D_1,
  noviembre_sur_P_2_D_2,
  noviembre_sur_P_2_D_3,
  noviembre_sur_P_3_D_1,
  noviembre_sur_P_3_D_2,
  noviembre_sur_P_3_D_3,
  noviembre_sur_P_4_D_1,
  noviembre_sur_P_4_D_2,
  noviembre_sur_P_4_D_3,
  noviembre_sur_P_5_D_1,
  noviembre_sur_P_5_D_2,
  noviembre_sur_P_5_D_3,
  noviembre_sur_P_6_D_1,
  noviembre_sur_P_6_D_2,
  noviembre_sur_P_6_D_3,
} from "./meses-estado/11-noviembre-sur.js";

import {
  diciembre_norte_P_1_D_1,
  //   diciembre_norte_P_1_D_2,
  diciembre_norte_P_1_D_3,
  diciembre_norte_P_2_D_1,
  diciembre_norte_P_2_D_2,
  diciembre_norte_P_2_D_3,
  diciembre_norte_P_3_D_1,
  diciembre_norte_P_3_D_2,
  diciembre_norte_P_3_D_3,
  diciembre_norte_P_4_D_1,
  diciembre_norte_P_4_D_2,
  diciembre_norte_P_4_D_3,
  diciembre_norte_P_5_D_1,
  diciembre_norte_P_5_D_2,
  diciembre_norte_P_5_D_3,
  diciembre_norte_P_6_D_1,
  diciembre_norte_P_6_D_2,
  diciembre_norte_P_6_D_3,
} from "./meses-estado/12-diciembre-norte.js";
import {
  diciembre_sur_P_1_D_1,
  //   diciembre_sur_P_1_D_2,
  diciembre_sur_P_1_D_3,
  diciembre_sur_P_2_D_1,
  diciembre_sur_P_2_D_2,
  diciembre_sur_P_2_D_3,
  diciembre_sur_P_3_D_1,
  diciembre_sur_P_3_D_2,
  diciembre_sur_P_3_D_3,
  diciembre_sur_P_4_D_1,
  diciembre_sur_P_4_D_2,
  diciembre_sur_P_4_D_3,
  diciembre_sur_P_5_D_1,
  diciembre_sur_P_5_D_2,
  diciembre_sur_P_5_D_3,
  diciembre_sur_P_6_D_1,
  diciembre_sur_P_6_D_2,
  diciembre_sur_P_6_D_3,
} from "./meses-estado/12-diciembre-sur.js";

const variablesEneroNorte = {
  enero_norte_P_1_D_1,
  //   enero_norte_P_1_D_2,
  enero_norte_P_1_D_3,
  enero_norte_P_2_D_1,
  enero_norte_P_2_D_2,
  enero_norte_P_2_D_3,
  enero_norte_P_3_D_1,
  enero_norte_P_3_D_2,
  enero_norte_P_3_D_3,
  enero_norte_P_4_D_1,
  enero_norte_P_4_D_2,
  enero_norte_P_4_D_3,
  enero_norte_P_5_D_1,
  enero_norte_P_5_D_2,
  enero_norte_P_5_D_3,
  enero_norte_P_6_D_1,
  enero_norte_P_6_D_2,
  enero_norte_P_6_D_3,
  enero_sur_P_1_D_1,
  //   enero_sur_P_1_D_2,
  enero_sur_P_1_D_3,
  enero_sur_P_2_D_1,
  enero_sur_P_2_D_2,
  enero_sur_P_2_D_3,
  enero_sur_P_3_D_1,
  enero_sur_P_3_D_2,
  enero_sur_P_3_D_3,
  enero_sur_P_4_D_1,
  enero_sur_P_4_D_2,
  enero_sur_P_4_D_3,
  enero_sur_P_5_D_1,
  enero_sur_P_5_D_2,
  enero_sur_P_5_D_3,
  enero_sur_P_6_D_1,
  enero_sur_P_6_D_2,
  enero_sur_P_6_D_3,
  febrero_norte_P_1_D_1,
  //   febrero_norte_P_1_D_2,
  febrero_norte_P_1_D_3,
  febrero_norte_P_2_D_1,
  febrero_norte_P_2_D_2,
  febrero_norte_P_2_D_3,
  febrero_norte_P_3_D_1,
  febrero_norte_P_3_D_2,
  febrero_norte_P_3_D_3,
  febrero_norte_P_4_D_1,
  febrero_norte_P_4_D_2,
  febrero_norte_P_4_D_3,
  febrero_norte_P_5_D_1,
  febrero_norte_P_5_D_2,
  febrero_norte_P_5_D_3,
  febrero_norte_P_6_D_1,
  febrero_norte_P_6_D_2,
  febrero_norte_P_6_D_3,
  febrero_sur_P_1_D_1,
  //   febrero_sur_P_1_D_2,
  febrero_sur_P_1_D_3,
  febrero_sur_P_2_D_1,
  febrero_sur_P_2_D_2,
  febrero_sur_P_2_D_3,
  febrero_sur_P_3_D_1,
  febrero_sur_P_3_D_2,
  febrero_sur_P_3_D_3,
  febrero_sur_P_4_D_1,
  febrero_sur_P_4_D_2,
  febrero_sur_P_4_D_3,
  febrero_sur_P_5_D_1,
  febrero_sur_P_5_D_2,
  febrero_sur_P_5_D_3,
  febrero_sur_P_6_D_1,
  febrero_sur_P_6_D_2,
  febrero_sur_P_6_D_3,
  marzo_norte_P_1_D_1,
  //   marzo_norte_P_1_D_2,
  marzo_norte_P_1_D_3,
  marzo_norte_P_2_D_1,
  marzo_norte_P_2_D_2,
  marzo_norte_P_2_D_3,
  marzo_norte_P_3_D_1,
  marzo_norte_P_3_D_2,
  marzo_norte_P_3_D_3,
  marzo_norte_P_4_D_1,
  marzo_norte_P_4_D_2,
  marzo_norte_P_4_D_3,
  marzo_norte_P_5_D_1,
  marzo_norte_P_5_D_2,
  marzo_norte_P_5_D_3,
  marzo_norte_P_6_D_1,
  marzo_norte_P_6_D_2,
  marzo_norte_P_6_D_3,
  marzo_sur_P_1_D_1,
  //   marzo_sur_P_1_D_2,
  marzo_sur_P_1_D_3,
  marzo_sur_P_2_D_1,
  marzo_sur_P_2_D_2,
  marzo_sur_P_2_D_3,
  marzo_sur_P_3_D_1,
  marzo_sur_P_3_D_2,
  marzo_sur_P_3_D_3,
  marzo_sur_P_4_D_1,
  marzo_sur_P_4_D_2,
  marzo_sur_P_4_D_3,
  marzo_sur_P_5_D_1,
  marzo_sur_P_5_D_2,
  marzo_sur_P_5_D_3,
  marzo_sur_P_6_D_1,
  marzo_sur_P_6_D_2,
  marzo_sur_P_6_D_3,
  abril_norte_P_1_D_1,
  //   abril_norte_P_1_D_2,
  abril_norte_P_1_D_3,
  abril_norte_P_2_D_1,
  abril_norte_P_2_D_2,
  abril_norte_P_2_D_3,
  abril_norte_P_3_D_1,
  abril_norte_P_3_D_2,
  abril_norte_P_3_D_3,
  abril_norte_P_4_D_1,
  abril_norte_P_4_D_2,
  abril_norte_P_4_D_3,
  abril_norte_P_5_D_1,
  abril_norte_P_5_D_2,
  abril_norte_P_5_D_3,
  abril_norte_P_6_D_1,
  abril_norte_P_6_D_2,
  abril_norte_P_6_D_3,

  abril_sur_P_1_D_1,
  //   abril_sur_P_1_D_2,
  abril_sur_P_1_D_3,
  abril_sur_P_2_D_1,
  abril_sur_P_2_D_2,
  abril_sur_P_2_D_3,
  abril_sur_P_3_D_1,
  abril_sur_P_3_D_2,
  abril_sur_P_3_D_3,
  abril_sur_P_4_D_1,
  abril_sur_P_4_D_2,
  abril_sur_P_4_D_3,
  abril_sur_P_5_D_1,
  abril_sur_P_5_D_2,
  abril_sur_P_5_D_3,
  abril_sur_P_6_D_1,
  abril_sur_P_6_D_2,
  abril_sur_P_6_D_3,

  junio_norte_P_1_D_1,
  //   junio_norte_P_1_D_2,
  junio_norte_P_1_D_3,
  junio_norte_P_2_D_1,
  junio_norte_P_2_D_2,
  junio_norte_P_2_D_3,
  junio_norte_P_3_D_1,
  junio_norte_P_3_D_2,
  junio_norte_P_3_D_3,
  junio_norte_P_4_D_1,
  junio_norte_P_4_D_2,
  junio_norte_P_4_D_3,
  junio_norte_P_5_D_1,
  junio_norte_P_5_D_2,
  junio_norte_P_5_D_3,
  junio_norte_P_6_D_1,
  junio_norte_P_6_D_2,
  junio_norte_P_6_D_3,

  junio_sur_P_1_D_1,
  //   junio_sur_P_1_D_2,
  junio_sur_P_1_D_3,
  junio_sur_P_2_D_1,
  junio_sur_P_2_D_2,
  junio_sur_P_2_D_3,
  junio_sur_P_3_D_1,
  junio_sur_P_3_D_2,
  junio_sur_P_3_D_3,
  junio_sur_P_4_D_1,
  junio_sur_P_4_D_2,
  junio_sur_P_4_D_3,
  junio_sur_P_5_D_1,
  junio_sur_P_5_D_2,
  junio_sur_P_5_D_3,
  junio_sur_P_6_D_1,
  junio_sur_P_6_D_2,
  junio_sur_P_6_D_3,

  julio_norte_P_1_D_1,
  //   julio_norte_P_1_D_2,
  julio_norte_P_1_D_3,
  julio_norte_P_2_D_1,
  julio_norte_P_2_D_2,
  julio_norte_P_2_D_3,
  julio_norte_P_3_D_1,
  julio_norte_P_3_D_2,
  julio_norte_P_3_D_3,
  julio_norte_P_4_D_1,
  julio_norte_P_4_D_2,
  julio_norte_P_4_D_3,
  julio_norte_P_5_D_1,
  julio_norte_P_5_D_2,
  julio_norte_P_5_D_3,
  julio_norte_P_6_D_1,
  julio_norte_P_6_D_2,
  julio_norte_P_6_D_3,

  julio_sur_P_1_D_1,
  //   julio_sur_P_1_D_2,
  julio_sur_P_1_D_3,
  julio_sur_P_2_D_1,
  julio_sur_P_2_D_2,
  julio_sur_P_2_D_3,
  julio_sur_P_3_D_1,
  julio_sur_P_3_D_2,
  julio_sur_P_3_D_3,
  julio_sur_P_4_D_1,
  julio_sur_P_4_D_2,
  julio_sur_P_4_D_3,
  julio_sur_P_5_D_1,
  julio_sur_P_5_D_2,
  julio_sur_P_5_D_3,
  julio_sur_P_6_D_1,
  julio_sur_P_6_D_2,
  julio_sur_P_6_D_3,

  agosto_norte_P_1_D_1,
  //   agosto_norte_P_1_D_2,
  agosto_norte_P_1_D_3,
  agosto_norte_P_2_D_1,
  agosto_norte_P_2_D_2,
  agosto_norte_P_2_D_3,
  agosto_norte_P_3_D_1,
  agosto_norte_P_3_D_2,
  agosto_norte_P_3_D_3,
  agosto_norte_P_4_D_1,
  agosto_norte_P_4_D_2,
  agosto_norte_P_4_D_3,
  agosto_norte_P_5_D_1,
  agosto_norte_P_5_D_2,
  agosto_norte_P_5_D_3,
  agosto_norte_P_6_D_1,
  agosto_norte_P_6_D_2,
  agosto_norte_P_6_D_3,

  agosto_sur_P_1_D_1,
  //   agosto_sur_P_1_D_2,
  agosto_sur_P_1_D_3,
  agosto_sur_P_2_D_1,
  agosto_sur_P_2_D_2,
  agosto_sur_P_2_D_3,
  agosto_sur_P_3_D_1,
  agosto_sur_P_3_D_2,
  agosto_sur_P_3_D_3,
  agosto_sur_P_4_D_1,
  agosto_sur_P_4_D_2,
  agosto_sur_P_4_D_3,
  agosto_sur_P_5_D_1,
  agosto_sur_P_5_D_2,
  agosto_sur_P_5_D_3,
  agosto_sur_P_6_D_1,
  agosto_sur_P_6_D_2,
  agosto_sur_P_6_D_3,

  septiembre_norte_P_1_D_1,
  //   septiembre_norte_P_1_D_2,
  septiembre_norte_P_1_D_3,
  septiembre_norte_P_2_D_1,
  septiembre_norte_P_2_D_2,
  septiembre_norte_P_2_D_3,
  septiembre_norte_P_3_D_1,
  septiembre_norte_P_3_D_2,
  septiembre_norte_P_3_D_3,
  septiembre_norte_P_4_D_1,
  septiembre_norte_P_4_D_2,
  septiembre_norte_P_4_D_3,
  septiembre_norte_P_5_D_1,
  septiembre_norte_P_5_D_2,
  septiembre_norte_P_5_D_3,
  septiembre_norte_P_6_D_1,
  septiembre_norte_P_6_D_2,
  septiembre_norte_P_6_D_3,

  septiembre_sur_P_1_D_1,
  //   septiembre_sur_P_1_D_2,
  septiembre_sur_P_1_D_3,
  septiembre_sur_P_2_D_1,
  septiembre_sur_P_2_D_2,
  septiembre_sur_P_2_D_3,
  septiembre_sur_P_3_D_1,
  septiembre_sur_P_3_D_2,
  septiembre_sur_P_3_D_3,
  septiembre_sur_P_4_D_1,
  septiembre_sur_P_4_D_2,
  septiembre_sur_P_4_D_3,
  septiembre_sur_P_5_D_1,
  septiembre_sur_P_5_D_2,
  septiembre_sur_P_5_D_3,
  septiembre_sur_P_6_D_1,
  septiembre_sur_P_6_D_2,
  septiembre_sur_P_6_D_3,

  octubre_norte_P_1_D_1,
  //   octubre_norte_P_1_D_2,
  octubre_norte_P_1_D_3,
  octubre_norte_P_2_D_1,
  octubre_norte_P_2_D_2,
  octubre_norte_P_2_D_3,
  octubre_norte_P_3_D_1,
  octubre_norte_P_3_D_2,
  octubre_norte_P_3_D_3,
  octubre_norte_P_4_D_1,
  octubre_norte_P_4_D_2,
  octubre_norte_P_4_D_3,
  octubre_norte_P_5_D_1,
  octubre_norte_P_5_D_2,
  octubre_norte_P_5_D_3,
  octubre_norte_P_6_D_1,
  octubre_norte_P_6_D_2,
  octubre_norte_P_6_D_3,

  octubre_sur_P_1_D_1,
  //   octubre_sur_P_1_D_2,
  octubre_sur_P_1_D_3,
  octubre_sur_P_2_D_1,
  octubre_sur_P_2_D_2,
  octubre_sur_P_2_D_3,
  octubre_sur_P_3_D_1,
  octubre_sur_P_3_D_2,
  octubre_sur_P_3_D_3,
  octubre_sur_P_4_D_1,
  octubre_sur_P_4_D_2,
  octubre_sur_P_4_D_3,
  octubre_sur_P_5_D_1,
  octubre_sur_P_5_D_2,
  octubre_sur_P_5_D_3,
  octubre_sur_P_6_D_1,
  octubre_sur_P_6_D_2,
  octubre_sur_P_6_D_3,

  noviembre_norte_P_1_D_1,
  //   noviembre_norte_P_1_D_2,
  noviembre_norte_P_1_D_3,
  noviembre_norte_P_2_D_1,
  noviembre_norte_P_2_D_2,
  noviembre_norte_P_2_D_3,
  noviembre_norte_P_3_D_1,
  noviembre_norte_P_3_D_2,
  noviembre_norte_P_3_D_3,
  noviembre_norte_P_4_D_1,
  noviembre_norte_P_4_D_2,
  noviembre_norte_P_4_D_3,
  noviembre_norte_P_5_D_1,
  noviembre_norte_P_5_D_2,
  noviembre_norte_P_5_D_3,
  noviembre_norte_P_6_D_1,
  noviembre_norte_P_6_D_2,
  noviembre_norte_P_6_D_3,

  noviembre_sur_P_1_D_1,
  //   noviembre_sur_P_1_D_2,
  noviembre_sur_P_1_D_3,
  noviembre_sur_P_2_D_1,
  noviembre_sur_P_2_D_2,
  noviembre_sur_P_2_D_3,
  noviembre_sur_P_3_D_1,
  noviembre_sur_P_3_D_2,
  noviembre_sur_P_3_D_3,
  noviembre_sur_P_4_D_1,
  noviembre_sur_P_4_D_2,
  noviembre_sur_P_4_D_3,
  noviembre_sur_P_5_D_1,
  noviembre_sur_P_5_D_2,
  noviembre_sur_P_5_D_3,
  noviembre_sur_P_6_D_1,
  noviembre_sur_P_6_D_2,
  noviembre_sur_P_6_D_3,

  diciembre_norte_P_1_D_1,
  //   diciembre_norte_P_1_D_2,
  diciembre_norte_P_1_D_3,
  diciembre_norte_P_2_D_1,
  diciembre_norte_P_2_D_2,
  diciembre_norte_P_2_D_3,
  diciembre_norte_P_3_D_1,
  diciembre_norte_P_3_D_2,
  diciembre_norte_P_3_D_3,
  diciembre_norte_P_4_D_1,
  diciembre_norte_P_4_D_2,
  diciembre_norte_P_4_D_3,
  diciembre_norte_P_5_D_1,
  diciembre_norte_P_5_D_2,
  diciembre_norte_P_5_D_3,
  diciembre_norte_P_6_D_1,
  diciembre_norte_P_6_D_2,
  diciembre_norte_P_6_D_3,

  diciembre_sur_P_1_D_1,
  //   diciembre_sur_P_1_D_2,
  diciembre_sur_P_1_D_3,
  diciembre_sur_P_2_D_1,
  diciembre_sur_P_2_D_2,
  diciembre_sur_P_2_D_3,
  diciembre_sur_P_3_D_1,
  diciembre_sur_P_3_D_2,
  diciembre_sur_P_3_D_3,
  diciembre_sur_P_4_D_1,
  diciembre_sur_P_4_D_2,
  diciembre_sur_P_4_D_3,
  diciembre_sur_P_5_D_1,
  diciembre_sur_P_5_D_2,
  diciembre_sur_P_5_D_3,
  diciembre_sur_P_6_D_1,
  diciembre_sur_P_6_D_2,
  diciembre_sur_P_6_D_3,
};

const depart = document.querySelectorAll(".container-departamento");

depart.forEach((depart) => {
  const img = depart.querySelector("img");
  img.addEventListener("click", clickDepart);
});

function clickDepart(event) {
  const departSelect = event.currentTarget.id;
  const data = departSelect.replace(
    /_(p|d)_/g,
    (match, p1) => `_${p1.toUpperCase()}_`
  );

  if (data in variablesEneroNorte) {
    const contenidoVariable = variablesEneroNorte[data];
    if (contenidoVariable.status === "Disponible") {
      const unidadCotizador = document.getElementById("unidad-cotizador");
      const areaCotizador = document.getElementById("area-cotizador");
      const precioCotizador = document.getElementById("precio-cotizador");
      const valorInput = document.getElementById("enganche-valor");

      const numeroFormateado = contenidoVariable.precio.toLocaleString(
        "es-MX",
        {
          style: "currency",
          currency: "MXN",
        }
      );
      valorInput.value = numeroFormateado;
      unidadCotizador.innerHTML = contenidoVariable.apto;
      areaCotizador.innerHTML = contenidoVariable.metros;
      precioCotizador.innerHTML = "$ " + contenidoVariable.precio;
      const modal = document.getElementById("modal-cotizador");
      modal.style.display = "block";
    }
  }
}
